### ISSUE TITLE
Some Faces won't load

### ISSUE THREAD

**Issue by MirariLP** [ArgoreOfficial/SprocketMeshConverter#1]
Like the title, some faces won't load (are black, not physically there) when using the "smooth" option. When using the "sharp" option, every face loads properly
![20220107233858_1](https://user-images.githubusercontent.com/88563201/148617015-d6073eff-8b29-4d89-8578-2a7582aeb1cd.jpg)
.

**Comment by ArgoreOfficial** [comment]
This is an issue with Sprocket itself. I believe it is due to textures not stretching properly, but I can't say with 100% certainty.

Unfortunately there's not much I can do about this.

**Comment by MirariLP** [comment]
Ah, ok, thanks for answering.
